language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "chrome-connect:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: XBxlpVxaq0GRS5FVV8Y40php5DkDtlptPKeHKbR6XmQcu2rRaEyiEYWZ3dmqJTlK/M8APbKJsPNC6RE/gdE5XzAjqqkgEv5e3G6reZGh0XjQV6HVUKg8uuQ648208yRogtiu56xFIXa+M5uUnPidSkP9AipJyzdDJz3hRM30jAgw5ky1T9+gsTIPGgN0P29XS4HiJPauRdQVL+3t1kjHEC1DbYlwClbo7IuqpGqsBT35H3sruNv6004BRrvsR393Y3CGJZwZi6v6C0t4v7pppHerzW1fcwXlK0Vy5pzXxQUDFPmpAwQ0ouliBjQPoMsGVzfC8UCLu2VWhkNuzofhP7Z/SZi9vprShU7Y+bZ8QUDbOnIfXToq8yxSlBBdCCxUPziCPoqfHBHQ/7j+W80pwrwj+eCpVQAHKWz13GgWMLwf8o8sapKdkQWNcd3mALzTM/zaGqa5FQYly24VTNGX3i0kWbtjHGjl9Zno4dnV9qxRuj15NxLc+6rLyhDpU11Nj0SosrRTUyTHyA9whMvUM5gHRWCs3C1ln86AwTL6yD6EPIG7AfPQT7iP+gmRKj4KPYCFkO5h7jbC9bp+8PWk/VOdKKOtmNM8KSE7A/Jm93d8VBXwsO5/kq2J6i2EGpwE0NXDlzAHHFRL9QzPhDCS0MmuAww/p+2kkLV5BL6WoVM=
  - secure: euIN4yuW2Cz/DWh9e3uPlsSl3Jby5DuT1h5xX8r6xp1EdoWg+lQOeWUCgVPYd6+j9C6oJhiLpwFOTXjZgRbXe4rx4l0zyQPb9hzq4f7F1BrCYIPRKaRVYnb8BDjuU6dMh2x9GYZJMrnDlZL5HAeiCUrpiFpYc1MGFxaVCrIEi/36c3Dgpd1MxO4LF7qaZCo7Uv35oIJQPpERn2Mg6LkSwcVgJmwfxFAur6gOZJQmjtJoRXbHSSSSjlFl45gg59WVXDbZpLY6vU+rOwtxWDrcv5uGpWMehiusTcJomKofDqqGYyPt9V6Y3N5ZdxsFfgU63jUZg1lkgZPHOcSxpl+IvMugmDwv58BQ01BjCzJ2IvjnJPnl2o/tyYV/Ttxifqd7oXkaO/HyiF/ZkdAtdXwlaOv9Ju72s1D8l26gX0l8ta7aKvB5CbrfAKBMPRlR/R4WDJPkeLDq/H6zcucHFBBM4Y0pRxu/DdMNwia3BfB1BfbYMDSJFH1aOow8aU35kwMqdCVXl5Hx5x/JMg/S6T+uMLlPj8lWRxxOkPYItcnMk0sWEuyX7m6P5MXbQkJDYadWUPRiYUVvCPkbNnjvVyfeWkuNZDb8o1BszA6IXlAEuiYJmCZAL53PWkjpQRJ2wX9ceLB9AvvoB0XdJpYeymUAbZdsth2+tA4IC7lK1H8z8cs=
